# Generated by Django 4.1.2 on 2023-01-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='foto')),
                ('keterangan', models.TextField()),
                ('harga', models.CharField(max_length=30)),
            ],
        ),
    ]
