# Generated by Django 4.1.2 on 2023-01-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='alamat',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='coordX',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='coordY',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='harga',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='home',
            name='keterangan',
            field=models.TextField(null=True),
        ),
    ]
