# Generated by Django 4.1.2 on 2023-01-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_home_alamat_home_coordx_home_coordy_alter_home_harga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
