# Generated by Django 4.1.2 on 2023-01-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_home_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='harga',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='nama',
            field=models.CharField(max_length=300),
        ),
    ]
