# Generated by Django 4.1.2 on 2023-01-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_home_harga_alter_home_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
